version: '3.8'

services:
  juice-shop:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - juice-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /juice-shop/logs

  # OWASP ZAP dla DAST
  zap:
    image: owasp/zap2docker-stable
    command: zap-baseline.py -t http://juice-shop:3000 -J zap-report.json
    depends_on:
      - juice-shop
    networks:
      - juice-network
    volumes:
      - ./security:/zap/wrk

networks:
  juice-network:
    driver: bridge
