name: DevSecOps

on: [push]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull Juice Shop image
        run: docker pull bkimminich/juice-shop

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bkimminich/juice-shop
          format: table
          severity: HIGH,CRITICAL
